language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: "pyF2bqgr6dWA1olc1bIyZoo6tMyRapyxkpDK/vIR7Eqy1rgeKrJF4FsdIbyYZ/Q+vVjGf+gfkCi7fnOAM8vAJN76AQw7aG9xai71TovP1EVmsfU9p1jzk4wVKN0IXUZ0o6iiA7U2sof9PMsWT78x0lpo5pFs626ywt
7Xvc+3uc/KoG/KsEUKNuRhbEARA2MCe1wONb87NPx1TX12qvIwIa3KncCCtIEfxtB54n/ldHz/2xS2zSgZAbKUrqoeCg/h5ofclc2hdN7C2xnGtudaz6hKFwAgXBEp4lAGSERveisBsexZYlNXO3i0ph6Ot1jB0p6F+PC8VIpLMs8
foB16idYOoLm23Cbu8Q8lGsYcDUyTfpS/ah/AbZjO/ocg6yVXS1WgVg9ikIbYcN1pQ/gEtU3Z0ORTD8HrV18eQrw5JIYTzZCfgfRW5JaJOIQunU49dl6lNWvzWOihwhVCE48ITnnY22E7vM2jPX8ViXl4t06/q55QK3JgjWhrhxEU
0PVCcQcsNgT9CVIMSj5S/vBCnGRFPRTjFszWmVnIIV24s5M6b6hBdisDAka0j4BObACENtyEpM/MMJYCGXB6KPgzQLJHEBSGxlGF7fTgg72FFG425XRClfwmlMBjPfokYYhtiuFGszIWlicIpskFhOIsUeNtATqVhc4fpSFLBkR1e
6o="
  app: thinkful-blog-api-challenge-jv
  on:
    repo: jbvance/thinkful-blog-api-challenge
